default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 1qazxsw2

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo_production
